# Model Output Summary
This notebook summarizes the performance and output count for each model based on the processed constraints CSV.

In [1]:
import pandas as pd

In [2]:
csv_path = "project_folder/LLM/New_documents_processed/all_processed_constraints.csv"
df = pd.read_csv(csv_path)

In [3]:
# Show available models
models = df[['model_type', 'model_name']].drop_duplicates().reset_index(drop=True)
models

  model_type               model_name
0     claude  claude-3-haiku-20240307
1   deepseek            deepseek-chat
2     gemini           gemini-1.5-pro
3     openai              gpt-4o-mini

In [4]:
# Count outputs for each model
output_counts = df.groupby(['model_type', 'model_name']).size().reset_index(name='output_count')
output_counts

  model_type               model_name  output_count
0     claude  claude-3-haiku-20240307           309
1   deepseek            deepseek-chat           234
2     gemini           gemini-1.5-pro           321
3     openai              gpt-4o-mini           158

In [5]:
# Summarize performance (basic: just output count per model for now)
for _, row in output_counts.iterrows():
    print(f"Model: {row['model_type']} / {row['model_name']} - Outputs: {row['output_count']}")

Model: claude / claude-3-haiku-20240307 - Outputs: 309
Model: deepseek / deepseek-chat - Outputs: 234
Model: gemini / gemini-1.5-pro - Outputs: 321
Model: openai / gpt-4o-mini - Outputs: 158